version: '3.4'

services:
  emailflowservice:
    image: emailflowservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8045:8045
      - 5005:5005
